ALTER TABLE "Wallet" ADD COLUMN IF NOT EXISTS "wallet_role" TEXT NOT NULL DEFAULT 'SOURCE';

ALTER TABLE "Deposit" ADD COLUMN IF NOT EXISTS "return_address" TEXT;
ALTER TABLE "Deposit" ADD COLUMN IF NOT EXISTS "ton_deposit_memo" TEXT;
ALTER TABLE "Deposit" ADD COLUMN IF NOT EXISTS "return_memo" TEXT;
