'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { useParams, useSearchParams } from 'next/navigation';
import {
  approveTraderPeriodReport,
  exportTraderReportCsv,
  generateTraderPayoutRegistry,
  getAdminPeriod,
  getPeriodCompletionReadiness,
  getPeriodTraderReports,
  getTraderPayoutRegistry,
  getTraderReportBuilder,
  markRemainingPayoutRegistryRowsAsPaid,
  previewTraderReport,
  publishTraderPeriodReport,
  saveTraderReportDraft,
  submitTraderReport,
  updatePayoutRegistryRow,
} from '../../../../lib/api';
import { StatusBadge } from '../../../../components/status-badge';
import {
  buildTraderReportForm,
  DEFAULT_TRADER_REPORT_FORM,
  getTraderReportActionAvailability,
} from '../../../../lib/trader-reporting.js';

const DEFAULT_FORM = DEFAULT_TRADER_REPORT_FORM;

const money = new Intl.NumberFormat('en-US', {
  minimumFractionDigits: 2,
  maximumFractionDigits: 2,
});

function toPayload(form: typeof DEFAULT_FORM) {
  return {
    ending_balance_usdt: Number(form.ending_balance_usdt || 0),
    trader_fee_percent: Number(form.trader_fee_percent || 40),
    network_fees_json: {
      TRON: Number(form.tron_fee || 0),
      TON: Number(form.ton_fee || 0),
      BSC: Number(form.bsc_fee || 0),
    },
  };
}

function formatMoney(value: number | null | undefined) {
  return money.format(Number(value || 0));
}

function formatTimestamp(value: string | null | undefined) {
  if (!value) return 'Not yet';
  return new Date(value).toLocaleString();
}

function getReferralModeMeta(mode: 'PROJECTED' | 'MATERIALIZED' | null | undefined) {
  if (mode === 'MATERIALIZED') {
    return {
      label: 'Materialized',
      tone: 'text-success bg-success/10',
      summary: 'Referral rewards are already written to the backend ledger and reflect the published state.',
      detail: 'Operators can verify final per-deposit referral amounts directly from materialized backend data.',
    };
  }

  return {
    label: 'Projected',
    tone: 'text-warning bg-warning/10',
    summary: 'Referral rewards are previewed for verification before publish and are not written to the ledger yet.',
    detail: 'Use these projected amounts to catch mistakes before publication. Final ledger rows appear only after publish.',
  };
}

function getReportTimeline(report: any) {
  if (!report) return [];

  return [
    { label: 'Generated by', value: report.generated_by || 'Unknown', at: report.created_at },
    { label: 'Approved by', value: report.approved_by || 'Pending', at: report.approved_at },
    { label: 'Published at', value: report.published_at ? 'Published' : 'Pending', at: report.published_at },
  ];
}

export default function PeriodReportingPage() {
  const params = useParams();
  const searchParams = useSearchParams();
  const periodId = params.id as string;

  const [period, setPeriod] = useState<any>(null);
  const [reports, setReports] = useState<any[]>([]);
  const [readiness, setReadiness] = useState<any>(null);
  const [selectedTraderId, setSelectedTraderId] = useState<string>('');
  const [form, setForm] = useState(DEFAULT_FORM);
  const [builder, setBuilder] = useState<any>(null);
  const [preview, setPreview] = useState<any>(null);
  const [registry, setRegistry] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [busyAction, setBusyAction] = useState('');
  const [rowDrafts, setRowDrafts] = useState<
    Record<string, { selected_payout_address: string; notes: string; tx_hash: string; failure_reason: string }>
  >({});

  const selectedReport = useMemo(
    () => reports.find((report) => report.trader_id === selectedTraderId) || null,
    [reports, selectedTraderId],
  );

  const currentView = preview || builder;
  const actionAvailability = getTraderReportActionAvailability(selectedReport, registry);
  const isFormEditable = actionAvailability.canSave && busyAction === '';
  const referralModeMeta = getReferralModeMeta(currentView?.referral_mode);

  function hydrateRowDrafts(nextRegistry: any) {
    setRowDrafts(Object.fromEntries((nextRegistry?.rows || []).map((row: any) => [
      row.payout_registry_row_id,
      {
        selected_payout_address: row.selected_payout_address || '',
        notes: row.notes || '',
        tx_hash: row.tx_hash || '',
        failure_reason: row.failure_reason || '',
      },
    ])));
  }

  async function loadTraderDetails(traderId: string, traderReportId?: string | null) {
    if (!traderId) {
      setBuilder(null);
      setPreview(null);
      setRegistry(null);
      setRowDrafts({});
      return;
    }

    const [nextBuilder, nextRegistry] = await Promise.all([
      getTraderReportBuilder(periodId, traderId),
      traderReportId ? getTraderPayoutRegistry(periodId, traderReportId) : Promise.resolve(null),
    ]);

    setBuilder(nextBuilder);
    setPreview(null);
    setRegistry(nextRegistry);
    hydrateRowDrafts(nextRegistry);
  }

  async function loadAll(preferredTraderId?: string) {
    if (!periodId) return;

    const [nextPeriod, nextReports, nextReadiness] = await Promise.all([
      getAdminPeriod(periodId),
      getPeriodTraderReports(periodId),
      getPeriodCompletionReadiness(periodId),
    ]);

    setPeriod(nextPeriod);
    setReports(nextReports);
    setReadiness(nextReadiness);

    const requestedTraderId = searchParams.get('traderId');
    const effectiveTraderId = preferredTraderId
      || requestedTraderId
      || selectedTraderId
      || nextReports[0]?.trader_id
      || '';
    const effectiveReport = nextReports.find((report: any) => report.trader_id === effectiveTraderId) || null;

    setSelectedTraderId(effectiveTraderId);
    setForm(buildTraderReportForm(effectiveReport));

    await loadTraderDetails(effectiveTraderId, effectiveReport?.trader_report_id);
  }

  async function handleSelectTrader(traderId: string) {
    const report = reports.find((item) => item.trader_id === traderId) || null;
    setSelectedTraderId(traderId);
    setForm(buildTraderReportForm(report));
    await loadTraderDetails(traderId, report?.trader_report_id);
  }

  useEffect(() => {
    loadAll()
      .catch(console.error)
      .finally(() => setLoading(false));
  }, [periodId]);

  const handlePreview = async () => {
    if (!selectedTraderId) return;

    setBusyAction('preview');
    try {
      const data = await previewTraderReport(periodId, selectedTraderId, toPayload(form));
      setPreview(data);
    } catch (err: any) {
      alert(err.response?.data?.message || 'Failed to build preview');
    } finally {
      setBusyAction('');
    }
  };

  const handleSave = async () => {
    if (!selectedTraderId) return;

    setBusyAction('save');
    try {
      await saveTraderReportDraft(periodId, selectedTraderId, toPayload(form));
      await loadAll(selectedTraderId);
    } catch (err: any) {
      alert(err.response?.data?.message || 'Failed to save draft');
    } finally {
      setBusyAction('');
    }
  };

  const handleWorkflow = async (action: 'submit' | 'approve' | 'publish' | 'registry' | 'csv') => {
    if (!selectedReport?.trader_report_id) return;

    setBusyAction(action);
    try {
      if (action === 'submit') {
        await submitTraderReport(periodId, selectedReport.trader_report_id);
      } else if (action === 'approve') {
        await approveTraderPeriodReport(periodId, selectedReport.trader_report_id);
      } else if (action === 'publish') {
        await publishTraderPeriodReport(periodId, selectedReport.trader_report_id);
      } else if (action === 'registry') {
        await generateTraderPayoutRegistry(periodId, selectedReport.trader_report_id);
      } else if (action === 'csv') {
        const csv = await exportTraderReportCsv(periodId, selectedReport.trader_report_id);
        const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
        const url = URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        link.download = `${selectedReport.trader_slug || selectedReport.trader_nickname}-report.csv`;
        link.click();
        URL.revokeObjectURL(url);
      }

      await loadAll(selectedTraderId);
    } catch (err: any) {
      alert(err.response?.data?.message || `Failed to ${action}`);
    } finally {
      setBusyAction('');
    }
  };

  const handleRowDraftChange = (
    rowId: string,
    field: 'selected_payout_address' | 'notes' | 'tx_hash' | 'failure_reason',
    value: string,
  ) => {
    setRowDrafts((prev) => ({
      ...prev,
      [rowId]: {
        selected_payout_address: prev[rowId]?.selected_payout_address || '',
        notes: prev[rowId]?.notes || '',
        tx_hash: prev[rowId]?.tx_hash || '',
        failure_reason: prev[rowId]?.failure_reason || '',
        [field]: value,
      },
    }));
  };

  const handleRowSave = async (rowId: string) => {
    const draft = rowDrafts[rowId];
    if (!draft) return;

    setBusyAction(`row-save-${rowId}`);
    try {
      const updatedRow = await updatePayoutRegistryRow(rowId, {
        selected_payout_address: draft.selected_payout_address,
        notes: draft.notes,
        tx_hash: draft.tx_hash,
        failure_reason: draft.failure_reason,
      });
      setRegistry((prev: any) => ({
        ...prev,
        rows: prev.rows.map((row: any) => row.payout_registry_row_id === rowId ? updatedRow : row),
      }));
    } catch (err: any) {
      alert(err.response?.data?.message || 'Failed to save registry row');
    } finally {
      setBusyAction('');
    }
  };

  const handleRowAction = async (rowId: string, action: 'PAID_MANUAL' | 'FAILED' | 'SKIPPED') => {
    setBusyAction(`row-${rowId}`);
    try {
      const data: any = { status: action };
      if (action === 'FAILED') data.failure_reason = rowDrafts[rowId]?.failure_reason || 'Marked failed by operator';
      const updatedRow = await updatePayoutRegistryRow(rowId, data);
      setRegistry((prev: any) => ({
        ...prev,
        rows: prev.rows.map((row: any) => row.payout_registry_row_id === rowId ? updatedRow : row),
      }));
    } catch (err: any) {
      alert(err.response?.data?.message || 'Failed to update registry row');
    } finally {
      setBusyAction('');
    }
  };

  const handleMarkRemainingPaid = async () => {
    if (!registry?.payout_registry_id) return;

    setBusyAction('bulk-paid');
    try {
      await markRemainingPayoutRegistryRowsAsPaid(registry.payout_registry_id, 'Marked via admin bulk action');
      await loadAll(selectedTraderId);
    } catch (err: any) {
      alert(err.response?.data?.message || 'Failed to mark remaining rows as paid');
    } finally {
      setBusyAction('');
    }
  };

  if (loading) return <div className="text-text-secondary">Loading...</div>;
  if (!period) return <div className="text-danger">Period not found</div>;

  return (
    <div className="space-y-6">
      <div className="flex items-start justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold">Trader Reporting</h1>
          <p className="mt-1 text-sm text-text-secondary">
            {period.title} · {new Date(period.start_date).toLocaleDateString()} - {new Date(period.end_date).toLocaleDateString()}
          </p>
        </div>
        <div className="text-right">
          <div className={`text-sm font-medium ${readiness?.ready ? 'text-success' : 'text-warning'}`}>
            {readiness?.ready ? 'Ready to complete period' : 'Completion blocked'}
          </div>
          {!!readiness?.blockers?.length && (
            <div className="mt-1 text-xs text-text-secondary">
              {readiness.blockers.join(', ')}
            </div>
          )}
        </div>
      </div>

      <div className="grid grid-cols-1 gap-6 xl:grid-cols-[320px,1fr]">
        <aside className="rounded-lg bg-bg-secondary p-4 space-y-3">
          <h2 className="font-semibold">Algorithms / Traders</h2>
          {reports.map((report) => (
            <button
              key={report.trader_id}
              onClick={() => handleSelectTrader(report.trader_id)}
              className={`w-full rounded-lg border px-3 py-3 text-left transition ${
                selectedTraderId === report.trader_id
                  ? 'border-primary bg-primary/10'
                  : 'border-gray-700 hover:border-gray-500'
              }`}
            >
              <div className="flex items-start justify-between gap-3">
                <div>
                  <div className="font-medium">{report.trader_display_name || report.trader_nickname}</div>
                  <div className="mt-1 text-xs text-text-secondary">@{report.trader_slug}</div>
                </div>
                <StatusBadge status={report.status} />
              </div>
            </button>
          ))}
        </aside>

        <section className="space-y-6">
          {selectedReport && currentView ? (
            <>
              <div className="rounded-lg bg-bg-secondary p-4">
                <div className="flex flex-wrap items-start justify-between gap-4">
                  <div>
                    <h2 className="text-xl font-semibold">{selectedReport.trader_display_name || selectedReport.trader_nickname}</h2>
                    <p className="mt-1 text-sm text-text-secondary">
                      Canonical workflow: cycle table → preview → submit → approve → publish → registry → complete period
                    </p>
                  </div>
                  <div className="flex flex-wrap gap-2">
                    <button onClick={handlePreview} disabled={busyAction !== '' || !actionAvailability.canPreview} className="px-3 py-2 bg-bg-tertiary rounded-lg text-sm disabled:opacity-50">
                      Preview
                    </button>
                    <button onClick={handleSave} disabled={busyAction !== '' || !actionAvailability.canSave} className="px-3 py-2 bg-primary text-white rounded-lg text-sm disabled:opacity-50">
                      Save For Review
                    </button>
                    {selectedReport.trader_report_id && (
                      <>
                        <button onClick={() => handleWorkflow('submit')} disabled={busyAction !== '' || !actionAvailability.canSubmit} className="px-3 py-2 bg-warning text-black rounded-lg text-sm disabled:opacity-50">
                          Submit
                        </button>
                        <button onClick={() => handleWorkflow('approve')} disabled={busyAction !== '' || !actionAvailability.canApprove} className="px-3 py-2 bg-success text-white rounded-lg text-sm disabled:opacity-50">
                          Approve
                        </button>
                        <button onClick={() => handleWorkflow('publish')} disabled={busyAction !== '' || !actionAvailability.canPublish} className="px-3 py-2 bg-link text-white rounded-lg text-sm disabled:opacity-50">
                          Publish
                        </button>
                        <button onClick={() => handleWorkflow('csv')} disabled={busyAction !== '' || !actionAvailability.canExportCsv} className="px-3 py-2 bg-bg-tertiary rounded-lg text-sm disabled:opacity-50">
                          Export CSV
                        </button>
                        <button onClick={() => handleWorkflow('registry')} disabled={busyAction !== '' || !actionAvailability.canGenerateRegistry} className="px-3 py-2 bg-danger text-white rounded-lg text-sm disabled:opacity-50">
                          Generate Registry
                        </button>
                      </>
                    )}
                  </div>
                </div>

                <div className="mt-4 grid grid-cols-1 gap-3 md:grid-cols-2 xl:grid-cols-4">
                  <div className="rounded-lg bg-bg-tertiary px-3 py-3">
                    <div className="text-xs text-text-secondary">Starting Balance</div>
                    <div className="mt-1 text-lg font-semibold">{formatMoney(currentView.starting_balance_usdt)}</div>
                  </div>
                  <div className="rounded-lg bg-bg-tertiary px-3 py-3">
                    <div className="text-xs text-text-secondary">Realized Algorithm Profit</div>
                    <div className="mt-1 text-lg font-semibold">{formatMoney(currentView.realized_profit_usdt)}</div>
                  </div>
                  <div className="rounded-lg bg-bg-tertiary px-3 py-3">
                    <div className="text-xs text-text-secondary">40% Fee</div>
                    <div className="mt-1 text-lg font-semibold">{formatMoney(currentView.trader_fee_usdt)}</div>
                  </div>
                  <div className="rounded-lg bg-bg-tertiary px-3 py-3">
                    <div className="text-xs text-text-secondary">Net Distributable</div>
                    <div className="mt-1 text-lg font-semibold">{formatMoney(currentView.net_distributable_usdt)}</div>
                  </div>
                </div>

                <div className="mt-4 grid grid-cols-1 gap-3 md:grid-cols-2 xl:grid-cols-3">
                  <div className="rounded-lg border border-gray-700 px-3 py-3 text-sm">
                    <div className="text-xs uppercase tracking-[0.18em] text-text-secondary">Formula</div>
                    <div className="mt-3 space-y-2">
                      <div className="flex items-center justify-between"><span className="text-text-secondary">Starting balance</span><span>{formatMoney(currentView.starting_balance_usdt)}</span></div>
                      <div className="flex items-center justify-between"><span className="text-text-secondary">Period balance before fees</span><span>{formatMoney(currentView.period_balance_before_fees_usdt)}</span></div>
                      <div className="flex items-center justify-between"><span className="text-text-secondary">Trader fee %</span><span>{currentView.trader_fee_percent}%</span></div>
                      <div className="flex items-center justify-between"><span className="text-text-secondary">Network fees</span><span>{formatMoney(currentView.total_network_fees_usdt)}</span></div>
                      <div className="flex items-center justify-between font-medium"><span>Distributable to users</span><span>{formatMoney(currentView.net_distributable_usdt)}</span></div>
                    </div>
                  </div>

                  <div className="rounded-lg border border-gray-700 px-3 py-3 text-sm">
                    <div className="text-xs uppercase tracking-[0.18em] text-text-secondary">Algorithm Metrics</div>
                    {currentView.metrics_summary ? (
                      <div className="mt-3 space-y-2">
                        <div className="flex items-center justify-between"><span className="text-text-secondary">Trades</span><span>{currentView.metrics_summary.trade_count}</span></div>
                        <div className="flex items-center justify-between"><span className="text-text-secondary">PnL</span><span>{formatMoney(currentView.metrics_summary.pnl)}</span></div>
                        <div className="flex items-center justify-between"><span className="text-text-secondary">Profit %</span><span>{currentView.metrics_summary.profit_percent}%</span></div>
                        <div className="flex items-center justify-between"><span className="text-text-secondary">Win rate</span><span>{currentView.metrics_summary.win_rate}%</span></div>
                        <div className="pt-2 text-xs text-text-secondary">
                          {currentView.metrics_summary.source_type || 'Unknown source'} · {formatTimestamp(currentView.metrics_summary.captured_at)}
                        </div>
                      </div>
                    ) : (
                      <div className="mt-3 text-text-secondary">No algorithm metrics captured yet.</div>
                    )}
                  </div>

                  <div className="rounded-lg border border-gray-700 px-3 py-3 text-sm">
                    <div className="text-xs uppercase tracking-[0.18em] text-text-secondary">Workflow State</div>
                    <div className="mt-3 space-y-2">
                      <div className="flex items-center justify-between"><span className="text-text-secondary">Report status</span><StatusBadge status={selectedReport.status} /></div>
                      <div className="flex items-center justify-between"><span className="text-text-secondary">Deposit rows</span><span>{currentView.deposit_count}</span></div>
                      <div className="flex items-center justify-between"><span className="text-text-secondary">Registry rows</span><span>{currentView.registry_summary.row_count}</span></div>
                      <div className="flex items-center justify-between"><span className="text-text-secondary">Registry pending</span><span>{currentView.registry_summary.pending_row_count}</span></div>
                    </div>
                  </div>
                </div>

                <div className="mt-4 rounded-lg border border-gray-700 px-4 py-4">
                  <div className="flex flex-wrap items-start justify-between gap-3">
                    <div>
                      <h3 className="font-semibold">Referral Verification</h3>
                      <p className="mt-1 text-sm text-text-secondary">{referralModeMeta.summary}</p>
                    </div>
                    <span className={`rounded px-3 py-1 text-xs font-medium ${referralModeMeta.tone}`}>
                      {referralModeMeta.label}
                    </span>
                  </div>
                  <p className="mt-3 text-xs text-text-secondary">{referralModeMeta.detail}</p>
                </div>

                <div className="mt-4 grid grid-cols-1 gap-3 md:grid-cols-2 xl:grid-cols-5">
                  <label className="text-sm">
                    <div className="mb-1 text-text-secondary">Ending balance USDT</div>
                    <input disabled={!isFormEditable} className="w-full px-3 py-2 bg-bg-tertiary rounded-lg disabled:opacity-50" value={form.ending_balance_usdt} onChange={(e) => setForm({ ...form, ending_balance_usdt: e.target.value })} />
                  </label>
                  <label className="text-sm">
                    <div className="mb-1 text-text-secondary">Trader fee %</div>
                    <input disabled={!isFormEditable} className="w-full px-3 py-2 bg-bg-tertiary rounded-lg disabled:opacity-50" value={form.trader_fee_percent} onChange={(e) => setForm({ ...form, trader_fee_percent: e.target.value })} />
                  </label>
                  <label className="text-sm">
                    <div className="mb-1 text-text-secondary">TRON fee</div>
                    <input disabled={!isFormEditable} className="w-full px-3 py-2 bg-bg-tertiary rounded-lg disabled:opacity-50" value={form.tron_fee} onChange={(e) => setForm({ ...form, tron_fee: e.target.value })} />
                  </label>
                  <label className="text-sm">
                    <div className="mb-1 text-text-secondary">TON fee</div>
                    <input disabled={!isFormEditable} className="w-full px-3 py-2 bg-bg-tertiary rounded-lg disabled:opacity-50" value={form.ton_fee} onChange={(e) => setForm({ ...form, ton_fee: e.target.value })} />
                  </label>
                  <label className="text-sm">
                    <div className="mb-1 text-text-secondary">BSC fee</div>
                    <input disabled={!isFormEditable} className="w-full px-3 py-2 bg-bg-tertiary rounded-lg disabled:opacity-50" value={form.bsc_fee} onChange={(e) => setForm({ ...form, bsc_fee: e.target.value })} />
                  </label>
                </div>

                {!actionAvailability.canSave && (
                  <p className="mt-3 text-xs text-text-secondary">
                    Published trader reports are read-only. You can still export CSV and complete payout-registry work from this screen.
                  </p>
                )}
              </div>

              <div className="rounded-lg bg-bg-secondary p-4">
                <div className="flex items-center justify-between gap-3">
                  <div>
                    <h3 className="font-semibold">User Cycles</h3>
                    <p className="mt-1 text-sm text-text-secondary">
                      Deposit-level drilldown for this trader inside the selected period, including {referralModeMeta.label.toLowerCase()} referral totals and payout allocation.
                    </p>
                  </div>
                  {preview && (
                    <span className="rounded bg-primary/10 px-3 py-1 text-xs text-primary">
                      Showing unsaved preview
                    </span>
                  )}
                </div>

                <div className="mt-4 overflow-x-auto">
                  <table className="w-full text-sm">
                    <thead className="text-text-secondary">
                      <tr>
                        <th className="p-2 text-left">Cycle</th>
                        <th className="p-2 text-left">User</th>
                        <th className="p-2 text-left">Network</th>
                        <th className="p-2 text-left">Asset</th>
                        <th className="p-2 text-right">Confirmed</th>
                        <th className="p-2 text-right">Referral ({referralModeMeta.label})</th>
                        <th className="p-2 text-right">Gross</th>
                        <th className="p-2 text-right">Fee</th>
                        <th className="p-2 text-right">Net</th>
                        <th className="p-2 text-left">Address Source</th>
                      </tr>
                    </thead>
                    <tbody>
                      {currentView.rows.map((row: any) => (
                        <tr key={row.deposit_id} className="border-t border-gray-700">
                          <td className="p-2 font-mono text-xs">{row.deposit_id.slice(0, 8)}...</td>
                          <td className="p-2">
                            <div className="font-medium">{row.user_label}</div>
                            <div className="text-xs text-text-secondary">{row.user_id}</div>
                          </td>
                          <td className="p-2">{row.network}</td>
                          <td className="p-2">{row.asset_symbol}</td>
                          <td className="p-2 text-right">{formatMoney(row.confirmed_amount_usdt)}</td>
                          <td className="p-2 text-right">
                            <div>{formatMoney(row.referral_reward_total_usdt)}</div>
                            <div className="text-xs text-text-secondary">
                              first {formatMoney(row.referral_first_deposit_usdt)} · profit {formatMoney(row.referral_period_profit_usdt)}
                            </div>
                            <div className="text-[11px] uppercase tracking-[0.18em] text-text-secondary">
                              {referralModeMeta.label}
                            </div>
                          </td>
                          <td className="p-2 text-right">{formatMoney(row.payout_gross_usdt)}</td>
                          <td className="p-2 text-right">{formatMoney(row.payout_fee_usdt)}</td>
                          <td className="p-2 text-right font-medium">{formatMoney(row.payout_net_usdt)}</td>
                          <td className="p-2">
                            <div>{row.address_source}</div>
                            <div className="text-xs text-text-secondary break-all">{row.selected_payout_address || 'No address yet'}</div>
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>

              <div className="rounded-lg bg-bg-secondary p-4">
                <h3 className="font-semibold">Report Timeline</h3>
                <div className="mt-3 grid grid-cols-1 gap-3 md:grid-cols-3">
                  {getReportTimeline(currentView.report).map((item) => (
                    <div key={item.label} className="rounded-lg border border-gray-700 px-3 py-3 text-sm">
                      <div className="text-xs uppercase tracking-[0.18em] text-text-secondary">{item.label}</div>
                      <div className="mt-2 font-medium">{item.value}</div>
                      <div className="mt-1 text-xs text-text-secondary">{formatTimestamp(item.at)}</div>
                    </div>
                  ))}
                </div>
              </div>

              {registry && (
                <div className="bg-bg-secondary rounded-lg p-4">
                  <div className="flex items-center justify-between mb-3">
                    <div>
                      <h3 className="font-semibold">Payout Registry</h3>
                      <p className="mt-1 text-sm text-text-secondary">
                        Manual row work for the published trader report. Registry progress feeds period completion readiness.
                      </p>
                    </div>
                    <button onClick={handleMarkRemainingPaid} disabled={busyAction !== '' || !actionAvailability.canMarkRemainingPaid} className="px-3 py-2 bg-success text-white rounded-lg text-sm disabled:opacity-50">
                      Mark Remaining as Paid
                    </button>
                  </div>

                  <div className="overflow-x-auto">
                    <table className="w-full text-sm">
                      <thead className="text-text-secondary">
                        <tr>
                          <th className="text-left p-2">Deposit</th>
                          <th className="text-left p-2">Owner</th>
                          <th className="text-left p-2">Net</th>
                          <th className="text-left p-2">Address</th>
                          <th className="text-left p-2">Notes</th>
                          <th className="text-left p-2">TX Hash</th>
                          <th className="text-left p-2">Failure</th>
                          <th className="text-left p-2">Status</th>
                          <th className="text-left p-2">Actions</th>
                        </tr>
                      </thead>
                      <tbody>
                        {registry.rows.map((row: any) => (
                          <tr key={row.payout_registry_row_id} className="border-t border-gray-700">
                            <td className="p-2 font-mono text-xs">{row.deposit_id.slice(0, 8)}...</td>
                            <td className="p-2">
                              <div className="font-medium">{row.user_label || 'Unknown user'}</div>
                              {row.user_id && (
                                <div className="text-xs text-text-secondary">{row.user_id}</div>
                              )}
                            </td>
                            <td className="p-2">{formatMoney(row.payout_net_usdt)}</td>
                            <td className="p-2">
                              <input
                                value={rowDrafts[row.payout_registry_row_id]?.selected_payout_address ?? row.selected_payout_address ?? ''}
                                onChange={(e) => handleRowDraftChange(row.payout_registry_row_id, 'selected_payout_address', e.target.value)}
                                className="w-full px-2 py-1 bg-bg-tertiary rounded text-xs"
                              />
                            </td>
                            <td className="p-2">
                              <input
                                value={rowDrafts[row.payout_registry_row_id]?.notes ?? row.notes ?? ''}
                                onChange={(e) => handleRowDraftChange(row.payout_registry_row_id, 'notes', e.target.value)}
                                className="w-full px-2 py-1 bg-bg-tertiary rounded text-xs"
                                placeholder="Optional note"
                              />
                            </td>
                            <td className="p-2">
                              <input
                                value={rowDrafts[row.payout_registry_row_id]?.tx_hash ?? row.tx_hash ?? ''}
                                onChange={(e) => handleRowDraftChange(row.payout_registry_row_id, 'tx_hash', e.target.value)}
                                className="w-full px-2 py-1 bg-bg-tertiary rounded text-xs font-mono"
                                placeholder="Transaction hash"
                              />
                            </td>
                            <td className="p-2">
                              <input
                                value={rowDrafts[row.payout_registry_row_id]?.failure_reason ?? row.failure_reason ?? ''}
                                onChange={(e) => handleRowDraftChange(row.payout_registry_row_id, 'failure_reason', e.target.value)}
                                className="w-full px-2 py-1 bg-bg-tertiary rounded text-xs"
                                placeholder="Failure reason"
                              />
                            </td>
                            <td className="p-2"><StatusBadge status={row.status} /></td>
                            <td className="p-2 space-x-2">
                              <button onClick={() => handleRowSave(row.payout_registry_row_id)} className="text-primary text-xs hover:underline">Save</button>
                              <button onClick={() => handleRowAction(row.payout_registry_row_id, 'PAID_MANUAL')} className="text-success text-xs hover:underline">Paid</button>
                              <button onClick={() => handleRowAction(row.payout_registry_row_id, 'FAILED')} className="text-danger text-xs hover:underline">Failed</button>
                              <button onClick={() => handleRowAction(row.payout_registry_row_id, 'SKIPPED')} className="text-warning text-xs hover:underline">Skip</button>
                            </td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                </div>
              )}
            </>
          ) : (
            <div className="rounded-lg bg-bg-secondary p-8 text-text-secondary">
              Select a trader to open the report builder.
            </div>
          )}

          <Link href="/periods" className="text-primary text-sm hover:underline">
            &larr; Back to Periods
          </Link>
        </section>
      </div>
    </div>
  );
}
